/**
 * Generated by MineCDL(https://github.com/superx101/MineCDL) v1.1.0
 * 
 * test2                     @(description="Test2 command")
 *     <number>: Int << 1
 *         f1()
 */

/**
 * An abstract class of register command in LLSE
 * @abstract
 */
abstract class Test2CommandAbstract {
    
    constructor() {}
    
    public register(): boolean {
        const command = mc.newCommand("test2", "Test2 command");
        undefined
        undefined
        command.mandatory("number", ParamType.Int, "", "mandatory_var_number");
        command.overload(["mandatory_var_number"]);
        command.setCallback((command, origin, output, result) => {
            this.callback(command, origin, output, result);
        });
        return command.setup();
    }
    
    public callback(command: Command, origin: CommandOrigin, output: CommandOutput, result: any): any {
        return this.f1(result.number);
    }
    
    protected abstract f1(number: number): any; 
}

export { Test2CommandAbstract };
